In [1]:
import numpy as np
series = [[23,45,12,679], [14,48,69,38]]
new_series = np.array(series)
print(new_series.ndim)
print(new_series.shape)

2
(2, 4)


In [2]:
a = np.zeros(10) + 4
a

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

In [3]:

a = np.zeros(10) * 4
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
a = np.ones(10) * 4
a

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

In [5]:
a= np.ones(10) + 4
a

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [6]:
a = np.full(10, 4)
a

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [7]:
import numpy as np
dataset = np.array(['paul', 'jacob', 'vince', 'paul', 'miky', 'larence', 'warren'])
print(dataset == 'paul')

[ True False False  True False False False]


In [8]:
import numpy as np

percentiles = [98, 76.37, 55.55, 69, 88]
first_subject = np.array(percentiles)
print(first_subject.dtype.name)

float64


In [10]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[::2] = -1
arr

array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9])

In [11]:
arr[1::2] = -1
arr

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [13]:
arr[arr % 2 == 0] = -1
arr

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [14]:
arr[-2::-2] = -1
arr

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [17]:
arr = np.eye(5)

arr[arr == 0] = -1
arr

array([[ 1., -1., -1., -1., -1.],
       [-1.,  1., -1., -1., -1.],
       [-1., -1.,  1., -1., -1.],
       [-1., -1., -1.,  1., -1.],
       [-1., -1., -1., -1.,  1.]])

In [18]:
arr[arr != 1] = -1
arr

array([[ 1., -1., -1., -1., -1.],
       [-1.,  1., -1., -1., -1.],
       [-1., -1.,  1., -1., -1.],
       [-1., -1., -1.,  1., -1.],
       [-1., -1., -1., -1.,  1.]])

In [19]:
arr = np.full((5x5),-1)
arr

SyntaxError: invalid syntax (<ipython-input-19-ddd7315b3015>, line 1)

In [20]:
arr = arr - (np.eye(5) + 1)
arr

array([[-1., -2., -2., -2., -2.],
       [-2., -1., -2., -2., -2.],
       [-2., -2., -1., -2., -2.],
       [-2., -2., -2., -1., -2.],
       [-2., -2., -2., -2., -1.]])